function eigenvalues = import_eigenvalues(input_file_path, startRow, endRow)
% IMPORTEIGENVALUES  Import orbital eigenvalues from Octopus TDDFT output.
%   Imports time-dependent Kohn-Sham orbital eigenvalues from an Octopus
%   eigenvalues output file. Each column corresponds to one orbital, each
%   row to one time step. Trailing NaN-only columns are removed.
%
%   Input arguments:
%       input_file_path - Path to the Octopus eigenvalues output file (string).
%       startRow        - First data row (default: 8, skips Octopus header).
%       endRow          - Last data row (default: inf, reads to end of file).
%
%   Output:
%       eigenvalues     - Numeric matrix [ntimesteps x norbitals] of orbital
%                         eigenvalues (in energy units as used by Octopus).
%
%   Usage:
%       eigvals = import_eigenvalues('td.general/eigenvalues');
%       eigvals = import_eigenvalues('td.general/eigenvalues', 8, 32556);
%
%   References:
%       Octopus code: https://octopus-code.org
%       Octopus variable: Eigenvalues (td.general/eigenvalues)
%       Uses MATLAB textscan for fixed-width column parsing.
%
%   Author: Auto-generated by MATLAB Import Tool on 2024/09/27
%   Refactored: 2025/07 - Cleaned auto-generated boilerplate, improved names.

%% Initialize variables.
if nargin <= 2
    startRow = 8;
    endRow = inf;
end

%% Format description.
% Each data line: %8f (step/state index) + M x %24f (eigenvalue per orbital) + trailing text.
% The number of %24f columns depends on the number of orbitals in the calculation.
% Trailing text column is discarded in output assembly.
formatSpec = '%8f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%24f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(input_file_path, 'r');

%% Read data columns according to format string.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
    'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', ...
    'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, ...
    'ReturnOnError', false, 'EndOfLine', '\r\n');
for block = 2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, ...
        endRow(block)-startRow(block)+1, 'Delimiter', '', ...
        'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, ...
        'HeaderLines', startRow(block)-1, 'ReturnOnError', false, ...
        'EndOfLine', '\r\n');
    for col = 1:length(dataArray)
        dataArray{col} = [dataArray{col}; dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Assemble output matrix and remove trailing NaN-only columns.
eigenvalues = [dataArray{1:end-1}];
cols_with_nan = any(isnan(eigenvalues), 1);
eigenvalues = eigenvalues(:, ~cols_with_nan);
end
