function density = import_density(input_file_path, grid_size, startRow, endRow)
% IMPORTDENSITY  Import electron density from Octopus cube-format output.
%   Imports real-space electron density from an Octopus-generated cube file.
%   The data is read as fixed-width text columns, converted to numeric
%   values, and then reshaped into a 3D array matching the simulation grid.
%
%   The density is stored in the cube file as a flattened 1D array in
%   Fortran column-major order (x fastest, then y, then z slowest).
%   Because the cube format writes 6 values per line, the intermediate
%   reshape pads the flat array to a multiple of 6 before reshaping to
%   the target 3D grid [grid_size x grid_size x grid_size].
%
%   Input arguments:
%       input_file_path - Path to the Octopus density cube file (string).
%       grid_size       - Number of grid points per dimension (scalar).
%                         Total voxels = grid_size^3.
%       startRow        - First data row (default: 58, skips cube header).
%       endRow          - Last data row (default: inf, reads to end of file).
%
%   Output:
%       density         - 3D numeric array [grid_size x grid_size x grid_size]
%                         containing the electron density on the real-space grid.
%
%   Usage:
%       rho = import_density('density.cube', 100);
%       rho = import_density('density.cube', 100, 58, 3208013);
%
%   References:
%       Octopus code: https://octopus-code.org
%       Gaussian cube format: http://paulbourke.net/dataformats/cube/
%       Uses MATLAB textscan with string conversion for numeric parsing.
%
%   Author: Auto-generated by MATLAB Import Tool on 2023/07/17
%   Refactored: 2025/07 - Cleaned auto-generated boilerplate, improved names.

%% Initialize variables.
if nargin <= 3
    startRow = 58;
    endRow = inf;
end

%% Format description.
% Cube format data lines: 6 columns of %15s (string-formatted floats) + trailing text.
% Values are read as strings and converted to double after trimming.
formatSpec = '%15s%15s%15s%15s%15s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(input_file_path, 'r');

%% Read data columns according to format string.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
    'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', ...
    'HeaderLines', startRow(1)-1, 'ReturnOnError', false, ...
    'EndOfLine', '\r\n');
for block = 2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, ...
        endRow(block)-startRow(block)+1, 'Delimiter', '', ...
        'WhiteSpace', '', 'TextType', 'string', ...
        'HeaderLines', startRow(block)-1, 'ReturnOnError', false, ...
        'EndOfLine', '\r\n');
    for col = 1:length(dataArray)
        dataArray{col} = [dataArray{col}; dataArrayBlock{col}];
    end
end

%% Trim whitespace from all cell columns.
dataArray{1} = strtrim(dataArray{1});
dataArray{2} = strtrim(dataArray{2});
dataArray{3} = strtrim(dataArray{3});
dataArray{4} = strtrim(dataArray{4});
dataArray{5} = strtrim(dataArray{5});
dataArray{6} = strtrim(dataArray{6});

%% Close the text file.
fclose(fileID);

%% Convert strings to numbers and reshape to 3D grid.
% Step 1: Concatenate all string columns and convert to double.
% Step 2: Pad flat array to multiple of 6 (cube format has 6 values/line).
% Step 3: Reshape to [grid_size x grid_size x grid_size] (Fortran order).
density_flat = str2double([dataArray{1:end-1}]);
density_flat = reshape(density_flat', ceil(grid_size/6)*6, grid_size^2);
density = reshape(density_flat(1:grid_size, :), grid_size, grid_size, grid_size);
end
