function energy_data = import_energy(input_file_path, startRow, endRow)
% IMPORTENERGY  Import total energy data from Octopus TDDFT output.
%   Imports time-dependent energy values from an Octopus energy output file.
%   Each row typically contains: time step index + energy components
%   (total, kinetic, Hartree, exchange-correlation, external, etc.).
%
%   Input arguments:
%       input_file_path - Path to the Octopus energy output file (string).
%       startRow        - First data row (default: 6, skips Octopus header).
%       endRow          - Last data row (default: inf, reads to end of file).
%
%   Output:
%       energy_data     - Numeric matrix [nrows x ncols] of energy values.
%                         Column 1: time step index.
%                         Columns 2-11: energy components (total, kinetic,
%                         Hartree, xc, int[n], exchange, corr., ext, ion-ion,
%                         total_again, zero).
%
%   Usage:
%       energy = import_energy('td.general/energy');
%       energy = import_energy('td.general/energy', 6, 32554);
%
%   References:
%       Octopus code: https://octopus-code.org
%       Octopus variable: Energy (td.general/energy)
%       Uses MATLAB textscan for fixed-width column parsing.
%
%   Author: Auto-generated by MATLAB Import Tool on 2024/09/27
%   Refactored: 2025/07 - Cleaned auto-generated boilerplate, improved names.

%% Initialize variables.
if nargin <= 2
    startRow = 6;
    endRow = inf;
end

%% Format description.
% Each data line: %8f (step) + 10x %24f (energy components) + trailing text.
% The trailing text column is discarded in output assembly.
formatSpec = '%8f%24f%24f%24f%24f%24f%24f%24f%24f%24f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(input_file_path, 'r');

%% Read data columns according to format string.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
    'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', ...
    'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, ...
    'ReturnOnError', false, 'EndOfLine', '\r\n');
for block = 2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, ...
        endRow(block)-startRow(block)+1, 'Delimiter', '', ...
        'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, ...
        'HeaderLines', startRow(block)-1, 'ReturnOnError', false, ...
        'EndOfLine', '\r\n');
    for col = 1:length(dataArray)
        dataArray{col} = [dataArray{col}; dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Assemble output matrix, discarding the trailing text column.
energy_data = [dataArray{1:end-1}];
end
