function ion_channels = import_ion_channels(input_file_path, startRow, endRow)
% IMPORTIONCH  Import ionization channel data from Octopus TDDFT output.
%   Imports time-dependent ionization probability per channel from an
%   Octopus ionization channels output file. Each column corresponds to
%   one ionization channel (Kohn-Sham state), each row to one time step.
%
%   Input arguments:
%       input_file_path - Path to the Octopus ion_channels output file (string).
%       startRow        - First data row (default: 6, skips Octopus header).
%       endRow          - Last data row (default: inf, reads to end of file).
%
%   Output:
%       ion_channels    - Numeric matrix [ntimesteps x nchannels] of
%                         ionization probabilities per channel.
%
%   Usage:
%       ionch = import_ion_channels('td.general/ion_ch');
%       ionch = import_ion_channels('td.general/ion_ch', 6, 1401);
%
%   References:
%       Octopus code: https://octopus-code.org
%       Octopus variable: IonizationChannels (td.general/ion_ch)
%       Uses MATLAB textscan for fixed-width column parsing.
%
%   Author: Auto-generated by MATLAB Import Tool on 2023/07/09
%   Refactored: 2025/07 - Cleaned auto-generated boilerplate, improved names.

%% Initialize variables.
if nargin <= 2
    startRow = 6;
    endRow = inf;
end

%% Format description.
% Each data line: %8f (time step) + M x %24f (ionization per channel) + trailing text.
% Trailing text column is discarded in output assembly.
formatSpec = '%8f%24f%24f%24f%24f%24f%24f%24f%24f%24f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(input_file_path, 'r');

%% Read data columns according to format string.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, ...
    'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', ...
    'HeaderLines', startRow(1)-1, 'ReturnOnError', false, ...
    'EndOfLine', '\r\n');
for block = 2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, ...
        endRow(block)-startRow(block)+1, 'Delimiter', '', ...
        'WhiteSpace', '', 'TextType', 'string', ...
        'HeaderLines', startRow(block)-1, 'ReturnOnError', false, ...
        'EndOfLine', '\r\n');
    for col = 1:length(dataArray)
        dataArray{col} = [dataArray{col}; dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Assemble output matrix, discarding the trailing text column.
ion_channels = [dataArray{1:end-1}];
end
