error(['Legacy regression entry only. Production population analysis must use ' ...
       'manifest-defined grids, moving projectile centers, multiple radii, and ' ...
       'moving-control-surface flux closure in src/lif_tddft/analysis/.']);
